version: "3"
services: 
    db:
        image: postgres:14.0
        environment:
            POSTGRES_PASSWORD: admin123
    # mysql:
    #     image: mysql:5.7
    #     command: --default-authentication-plugin=mysql_native_password
    #     environment:
    #         MYSQL_ROOT_PASSWORD: admin123
    adminer:
        image: adminer
        ports:
            - 8080:8080
    api:
        build: 
            context: ./api
        tty: true
        volumes: 
            - ./api:/app
        ports:
            - 8000:5000
        environment: 
            - APP_SETTINGS=config.DevelopmentConfig
            - DATABASE_URI=postgresql+pg8000://postgres:admin123@db/lahaus
            #- DATABASE_URI=postgresql://postgres:admin123@db/lahaus